INSERT INTO associations (id, name, description) VALUES ( 'null', 'Alliance MMA', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Law MMA', 'Longo and Weidman MMA' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Kings MMA', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Nova Uniao', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Team Alpha Male', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Tiger Muay Thai', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Roufusport', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'SBG Ireland', 'Straight Blast Gym Ireland' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Jackson-Wink MMA', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'AKA', 'American Kickboxing Academy' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Hard Knocks 365', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'ATT', 'American Top Team' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Team Elevation', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Gracie Barra', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'S4 Fight Team', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Arrachion MMA', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Poland Top Team', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Ankos Zapasy', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Silesian Cage Club', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Berkut WCA Fight Team', 'null' );
INSERT INTO associations (id, name, description) VALUES ( 'null', 'Berserkers Team', 'null' );

INSERT INTO organizations(id, name, description) VALUES ( 'null', 'UFC', 'Ultimate Fighting Championship' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'Bellator MMA', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'ACB', 'Absolute Fighting Championship' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'FNG', 'Fight Nights Global' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'ONE Championship', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'Rizin FF', 'Rizin Fighting Federation' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'Invicta FC', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'Pancrase', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'M-1 Global', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'UFC', 'null' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'LFA', 'Legacy Fighting Alliance' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'WFCA', 'World Fighting Championship Akhmat' );
INSERT INTO organizations(id, name, description) VALUES ( 'null', 'KSW', 'Konfrontacja Sztuk Walki' );

INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Submission', 'null' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'KO', 'null' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'TKO', 'null' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Decision', 'Unanimous' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Decision', 'Split' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Decision', 'Majority' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Draw', 'Unanimous' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Draw', 'Majority' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Draw', 'Split' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Disqualification', 'null' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'Forfeit', 'null' );
INSERT INTO result_types(id, description, additional_info) VALUES ( 'null', 'No contest', 'null' );

INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', 'null', '52.2 ', 'Strawweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '52.2 ', '56.7', 'Flyweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '56.7', '61.2', 'Bantamweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '61.2 ', '65.8', 'Featherweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '65.8 ', '70.3', 'Lightweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '70.3 ', '77.1', 'Welterweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '77.1 ', '83.9', 'Middleweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '83.9 ', '93.0', 'Light Heavyweight', 'null' );
INSERT INTO weightclasses(id, lower_limit, upper_limit, name, organization_id) VALUES ( 'null', '93.9 ', '120.2', 'Heavyweight', 'null' );


INSERT INTO countries(id, name) VALUES ( 'null', 'Afghanistan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Albania' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Algeria' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Andorra' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Angola' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Argentina' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Armenia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Australia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Austria' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Azerbaijan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bahamas' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bahrain' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bangladesh' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Barbados' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Belarus' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Belgium' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Belize' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Benin' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bhutan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bolivia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bosnia Herzegovina' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Botswana' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Brazil' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Brunei' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Bulgaria' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Burkina' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Burundi' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Cambodia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Cameroon' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Canada' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Cape Verde' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Central African Rep' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Chad' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Chile' );
INSERT INTO countries(id, name) VALUES ( 'null', 'China' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Colombia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Comoros' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Congo' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Congo {Democratic Rep}' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Costa Rica' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Croatia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Cuba' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Cyprus' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Czech Republic' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Denmark' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Djibouti' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Dominica' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Dominican Republic' );
INSERT INTO countries(id, name) VALUES ( 'null', 'East Timor' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ecuador' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Egypt' );
INSERT INTO countries(id, name) VALUES ( 'null', 'El Salvador' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Equatorial Guinea' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Eritrea' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Estonia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ethiopia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Fiji' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Finland' );
INSERT INTO countries(id, name) VALUES ( 'null', 'France' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Gabon' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Gambia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Georgia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Germany' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ghana' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Greece' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Grenada' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Guatemala' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Guinea' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Guinea-Bissau' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Guyana' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Haiti' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Honduras' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Hungary' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Iceland' );
INSERT INTO countries(id, name) VALUES ( 'null', 'India' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Indonesia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Iran' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Iraq' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ireland {Republic}' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Israel' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Italy' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ivory Coast' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Jamaica' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Japan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Jordan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kazakhstan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kenya' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kiribati' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Korea North' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Korea South' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kosovo' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kuwait' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Kyrgyzstan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Laos' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Latvia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Lebanon' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Lesotho' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Liberia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Libya' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Liechtenstein' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Lithuania' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Luxembourg' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Macedonia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Madagascar' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Malawi' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Malaysia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Maldives' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mali' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Malta' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Marshall Islands' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mauritania' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mauritius' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mexico' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Micronesia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Moldova' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Monaco' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mongolia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Montenegro' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Morocco' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Mozambique' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Myanmar, {Burma}' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Namibia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Nauru' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Nepal' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Netherlands' );
INSERT INTO countries(id, name) VALUES ( 'null', 'New Zealand' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Nicaragua' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Niger' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Nigeria' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Norway' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Oman' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Pakistan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Palau' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Panama' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Papua New Guinea' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Paraguay' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Peru' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Philippines' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Poland' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Portugal' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Qatar' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Romania' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Russian Federation' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Rwanda' );
INSERT INTO countries(id, name) VALUES ( 'null', 'St Lucia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Samoa' );
INSERT INTO countries(id, name) VALUES ( 'null', 'San Marino' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Saudi Arabia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Senegal' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Serbia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Seychelles' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Sierra Leone' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Singapore' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Slovakia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Slovenia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Solomon Islands' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Somalia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'South Africa' );
INSERT INTO countries(id, name) VALUES ( 'null', 'South Sudan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Spain' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Sri Lanka' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Sudan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Suriname' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Swaziland' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Sweden' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Switzerland' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Syria' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Taiwan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Tajikistan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Tanzania' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Thailand' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Togo' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Tonga' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Tunisia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Turkey' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Turkmenistan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Tuvalu' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Uganda' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Ukraine' );
INSERT INTO countries(id, name) VALUES ( 'null', 'United Arab Emirates' );
INSERT INTO countries(id, name) VALUES ( 'null', 'United Kingdom' );
INSERT INTO countries(id, name) VALUES ( 'null', 'United States' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Uruguay' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Uzbekistan' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Vanuatu' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Vatican City' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Venezuela' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Vietnam' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Yemen' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Zambia' );
INSERT INTO countries(id, name) VALUES ( 'null', 'Zimbabwe' );